# Calvin Kuo _config.yml 
name: Calvin Kuo
markdown: CommonMarkGhPages
# Import theme
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: CALVIN KUO
description: Customer-Obsessed Innovator | Visionary Product Strategist | Impact-Driven Leader
